apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      targetPort: 9113
  namespaceSelector:
    matchNames:
      - default
