apiVersion: v1
kind: Pod
metadata:
  name: nginx-podmetrics
  labels:
    app: nginx-podmetrics
spec:
  containers:
  - name: nginx-podmetrics
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    volumeMounts:
    - name: nginx-podmetrics-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
  - name: nginx-podmetrics-exporter
    image: nginx/nginx-prometheus-exporter:1.5
    args:
    - '-nginx.scrape-uri=http://localhost/metrics'
    ports:
    - containerPort: 9113
      name: metrics
    resources:
      requests:
        cpu: "0.05"
        memory: "64Mi"
      limits:
        cpu: "0.3"
        memory: "128Mi"
  volumes:
  - configMap:
      defaultMode: 420
      name: nginx-podmetrics-config
    name: nginx-podmetrics-config