apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 9113
    name: metrics
    targetPort: 9113
  type: ClusterIP 
  