# config-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane # Nó do Control Plane (Mestre)
  image: kindest/node:v1.28.0 # Versão do K8s
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
  # Alocação de Recursos para o nó Control Plane
  resources:
    requests:
      cpu: "200m" # 0.2 CPU
      memory: "512Mi" # 512 MB
    limits:
      cpu: "500m" # 0.5 CPU
      memory: "1Gi" # 1 GB
- role: worker # Nó Worker (Trabalhador)
  image: kindest/node:v1.28.0
  # Alocação de Recursos para o nó Worker
  resources:
    requests:
      cpu: "100m" # 0.1 CPU
      memory: "256Mi" # 256 MB
    limits:
      cpu: "300m" # 0.3 CPU
      memory: "1Gi"
- role: worker # Outro nó Worker
  image: kindest/node:v1.28.0
  # Alocação de Recursos para o segundo nó Worker
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "1Gi"