# Build Stage
FROM golang:1.25 AS builder

WORKDIR /app

COPY src/go.mod .
COPY src/main.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o main .


# Final stage
FROM alpine:3.23.3

COPY --from=builder /app/main /

CMD ["/main"]