apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
# TLS certificate and private key
# kubectl create secret tls tls-secret --cert=path/to/tls.crt --key=path/to/tls.key
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmekNDQW1lZ0F3SUJBZ0lVRFQ5ci81NUpa
    U3h1U2JMZUE2TWUrQ0V5Wndvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1R6RUxNQWtHQTFVRUJoTUNV
    RlF4RHpBTkJnTlZCQWdNQmt4cGMySnZZVEVSTUE4R0ExVUVCd3dJVDJScApkbVZzWVhNeER6QU5C
    Z05WQkFvTUJtazVkR1ZqYURFTE1Ba0dBMVVFQ3d3Q1ZFa3dIaGNOTWpZd01URXpNakl3Ck9ESXlX
    aGNOTWpjd01URXpNakl3T0RJeVdqQlBNUXN3Q1FZRFZRUUdFd0pRVkRFUE1BMEdBMVVFQ0F3R1RH
    bHoKWW05aE1SRXdEd1lEVlFRSERBaFBaR2wyWld4aGN6RVBNQTBHQTFVRUNnd0dhVGwwWldOb01R
    c3dDUVlEVlFRTApEQUpVU1RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dn
    RUJBTTI2aUtqcytTSW1hUGxRCmwzUnQ0MGhNUUp6WXRKcFJ2eHlaSXhacnphUGRrUTJxSFhWc005
    ODdiV3V4R0tIVU9PcXUwUkJkSjhReDI4S3kKeVMwZ1pOVkpneVdqYVZxUkg3aGY2Y0l0RE1jSHVn
    cThaL3lFbkJxMjFiVldZeVRKbDBvUlltS1ZFNmF1cTR5RQpxaDRrMDFyZVhpUWtSa1VrZzJiYmVY
    TTYzM05QTVlCZ0E4czhvbGhZaU11SDFsTjR5MFlBMmFadmc3NjR5bEp1Cm5EN2hnVGxwNWI5bFA1
    ZTF6R2RVNXdWNmFlc0R5WlI5UUE2YSs1OXNSN2l2MCttMy9BS0phc0g3ME1jekQ4UCsKT1RZSTY5
    NVM1ZVhwSDJxL0w0RTVmSS93SkpVWmt1RTBTaWpVRDVXQmlsR3JIN3paUS9Jdk41SUVOMEpxalRk
    RgpUekorK1M4Q0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZORlVRV2J2bFIrNFZJMjljUGJ2VW1Y
    UE9UMG9NQjhHCkExVWRJd1FZTUJhQUZORlVRV2J2bFIrNFZJMjljUGJ2VW1YUE9UMG9NQThHQTFV
    ZEV3RUIvd1FGTUFNQkFmOHcKRFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtXL05FU3h3a0wvOUg5
    S0xSVTZtaDV3emtvcCt6VzlQdHZ1ckphQQpRcElWcWlIakxlbmE3dE80QzhhcjRmbDlPL1oyRVZw
    ZWNNeVNkRVBXYmhPdm9iS29MeEpQTkdIdnlwY295NzZQClJWd0MyRGZXS05GUmFHSlJhUnM1ejNW
    a1NrZVhlZXRBcUxWTldMWXdsaWVLWTlJR1Vya01Hajc5QVJ6MnpSWksKL1lIODVJa2QxQklQaml0
    V1NGMVdKSFVXaENqWFROOTJ1OGsyN3M4b0thVmJUK252Y2pUQm9XOUh5QWNidVhNcwpvMVlBbGxT
    UTl1aWNQRXZRcjVsU0dPM0U1b1RYK0RwNUdEcG1YaUJSV2c4UGtjRmdiTTJtL1JnSGcxVTNxMEJ6
    CkRmdWltb0crazduSzdLRm9tNWZDL0NOR0RzdkduQlV3YmNuMVlJd25ITUZ3OHZRPQotLS0tLUVO
    RCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRRE51b2lvN1BraUptajUKVUpkMGJlTklURUNjMkxTYVViOGNt
    U01XYTgyajNaRU5xaDExYkRQZk8yMXJzUmloMURqcXJ0RVFYU2ZFTWR2Qwpzc2t0SUdUVlNZTWxv
    Mmxha1IrNFgrbkNMUXpIQjdvS3ZHZjhoSndhdHRXMVZtTWt5WmRLRVdKaWxST21ycXVNCmhLb2VK
    Tk5hM2w0a0pFWkZKSU5tMjNsek90OXpUekdBWUFQTFBLSllXSWpMaDlaVGVNdEdBTm1tYjRPK3VN
    cFMKYnB3KzRZRTVhZVcvWlQrWHRjeG5WT2NGZW1uckE4bVVmVUFPbXZ1ZmJFZTRyOVBwdC93Q2lX
    ckIrOURITXcvRAovamsyQ092ZVV1WGw2UjlxdnkrQk9YeVA4Q1NWR1pMaE5Fb28xQStWZ1lwUnF4
    KzgyVVB5THplU0JEZENhbzAzClJVOHlmdmt2QWdNQkFBRUNnZ0VBWGhUQVcxUW5xSFRkUzZxTjRK
    cENOclZjVlA0TE5ZbE50eFBYQm5GZFZPTkYKNnZSUlRYb2lqS00rS21JT0xDK0RxZHN4VTJUdWd4
    dno3bWxaYzlBZEhLYm1HVWZPTGJNeFNOMWY1c000VlNxVQo2MFQyM3ZWNytBR0Y0TXcxUWNVSThU
    L2ErTTlJOGRCdU5qQVRKZjdjUXZGdkp1TUoyYVBWamF1dnNrRUpuODZVClZ1NTZ6WGkyYmNKQTdF
    YkZFejl6bGZ4RDc0aGNLeVowS2ZwWUNKR3FtaC9rcnh2Z24zTm1oUjBHMHZjZ1ZMaGMKMngzMFlN
    VjBoZTFOQWkrYm5BZGJZaGpTRlYzR0RpVFZCVnVkNHJiM2hrbDA5VzZpNUlidW13MmZCb2k2ZzJn
    RQpKOUhYd3JiS25PUnNST3IwcTBJa2pEYVFqNHRVMHRrRG5KNGRnTWR1K1FLQmdRRDZiazBvYVo4
    NUJualNTc1NCCkZUaFAzUURVYWJub0twaHR4enIxdi9mRGI2TXpmWlVKN1I4NW03RGtlRFJ6SHg0
    NDdQeXVJdkNPM2hXeHV3NFoKclRkWFdLeDMxWjVENFBPdzdFM1lRRXdPcEtPd0tLM0RJdkI5cHAw
    TG8yM0Z5T3Y1TnVFQndWZ3ZOR1VmaUlDVQp2NkdNMXB0dG5zQTBXdjNvbjlVdlExZlZ0d0tCZ1FE
    U1RiNVVpcndTbzNpenk0VEVIRVhMNUJJVkp2RktseEJRCksvQ2xDQlpaWG56ZUUzN0ltVE9ISzRp
    MkRFSm5aUmhub09mRmNUODlteHBJSlZIbDhGN09UeU84cXp4bWpVL2UKRDcwWVpqcTNURUVad2VZ
    czNrTlNpb2poUHc4RW9DaDJQV242UHpSMHpaM0h3V0Rqa3RoRFY4VWFLMFFsRmlQNApZRlE5UGVV
    NFNRS0JnUUNLREluT0VFTnNiUXZuYUwzZ0puRnZYUFhiSWhrUVNZTFRhVE13UzAxcVY3MFFZbGJw
    CkxPUzhuZjJxUkRVdGpPYmRISTdCODVMR1B0aVlxL08rNWNTUEN0dXdCM3NDRWh4ajJDK2xXUFJV
    VWgvRnVQYm8KamZjaVhObFBsQnlzSGZFdTVUaXQvZ1g5cDVWakI1MVI0ajFNNVBTelBnTFlHWnpF
    UW0rRGFVMGZDd0tCZ1FDLwp2WElTMG9xMjA2UnhDTlY3bCt0ckFmNGFtdTdUK3ZjOG9WTStwQ2o4
    UWxIR2lDL0g1U1k5ejB0Tjc4OTdSWWtDCnNvbWVVcW8rR1BQVlkzRlFHOS9VYWdORE9UeFFvL1ox
    bUJQbjh3MEZvZGlaQzFnNUFFeVJMUTJ2a0RhNUdPekwKSVNOR3JlbTl0TnB1RGJtd3cybTV2SVJR
    WDdJNXZmMzlycFlmWUJkbFFRS0JnSGZmNHFQR2lGQlpTUVYreitmawpIWEV4S2phTWxTMGMyS0pC
    MlhxaTZ5S1dETU45MEUybzRrV3g3UklZbEt0UFNCM29jT0NTNFkxMk5PMzhRQk9YCnF4L1dxbjZw
    YTBqRW1uVWx5c2JObmx6THFwWFB3V0xUTDdaR0ZRS0ZIaHJvOThyZ3Z3d0hLOCt3c2gvNTJsS08K
    a3piT2ZsZVZ3d3FjTGpTSWZOUG1aNlBHCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K